using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BlazorCloud.Data.Entities;

[Table("EnvironmentData")]
public class EnvironmentData
{
    [Key] // Indicates that this property is the primary key
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // Auto-generated by the database
    public int Id { get; set; }

    [Required] // Makes the team number a required field
    public int TeamNumber { get; set; }

    [Required] // Makes the temperature a required field
    public float Temperature { get; set; }

    [Required] // Makes the humidity a required field
    public float Humidity { get; set; }

    [Required] // Makes the timestamp a required field
    public DateTime Timestamp { get; set; }
    
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
}